#ifndef _JISHI_S3_BOARD_CONFIG_H_
#define _JISHI_S3_BOARD_CONFIG_H_

#include <esp_camera.h>
#include <driver/gpio.h>
#include <driver/i2s_std.h>
#include <esp_adc/adc_oneshot.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_45
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_46
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_1
#define AUDIO_I2S_MIC_SLOT_MASK I2S_STD_SLOT_LEFT

#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_4
#define AUDIO_I2S_SPK_SLOT_MASK I2S_STD_SLOT_LEFT

#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_17
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_16
#define AUDIO_CODEC_TLV320_ADDR 0x4C

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#define LED_GPIO            GPIO_NUM_2
#define LED_STRIP_MAX_LEDS  5
#define LED_EYE_START       0
#define LED_EYE_COUNT       2
#define LED_BODY_START      2
#define LED_BODY_COUNT      3

#define DISPLAY_SDA_PIN     GPIO_NUM_17
#define DISPLAY_SCL_PIN     GPIO_NUM_16
#define DISPLAY_I2C_ADDRESS 0x3D
#define DISPLAY_WIDTH       128
#define DISPLAY_HEIGHT      64
#define DISPLAY_MIRROR_X    true
#define DISPLAY_MIRROR_Y    true

#define BATTERY_CHARGING_PIN             GPIO_NUM_7
#define BATTERY_ADC_PIN                  GPIO_NUM_8
#define BATTERY_ADC_CHANNEL              ADC_CHANNEL_7
#define BATTERY_ADC_UPPER_RESISTOR_OHM   100000.0f
#define BATTERY_ADC_LOWER_RESISTOR_OHM   100000.0f

#define CAMERA_PIN_D0       GPIO_NUM_47
#define CAMERA_PIN_D1       GPIO_NUM_38
#define CAMERA_PIN_D2       GPIO_NUM_40
#define CAMERA_PIN_D3       GPIO_NUM_39
#define CAMERA_PIN_D4       GPIO_NUM_48
#define CAMERA_PIN_D5       GPIO_NUM_21
#define CAMERA_PIN_D6       GPIO_NUM_12
#define CAMERA_PIN_D7       GPIO_NUM_11
#define CAMERA_PIN_PCLK     GPIO_NUM_14
#define CAMERA_PIN_HREF     GPIO_NUM_10
#define CAMERA_PIN_VSYNC    GPIO_NUM_15
#define CAMERA_PIN_XCLK     GPIO_NUM_13
#define CAMERA_PIN_SIOD     GPIO_NUM_17
#define CAMERA_PIN_SIOC     GPIO_NUM_16
#define CAMERA_PIN_PWDN     GPIO_NUM_9
#define CAMERA_PIN_RESET    GPIO_NUM_3
#define CAMERA_PIN_LDO_EN   GPIO_NUM_18
#define CAMERA_SCCB_I2C_PORT I2C_NUM_1
#define CAMERA_XCLK_LEDC_TIMER LEDC_TIMER_2
#define CAMERA_XCLK_LEDC_CHANNEL LEDC_CHANNEL_2
#define CAMERA_XCLK_FREQ_HZ 20000000
#define CAMERA_FRAME_SIZE   FRAMESIZE_VGA
#define CAMERA_PIXEL_FORMAT PIXFORMAT_JPEG
#define CAMERA_JPEG_QUALITY 10
#define CAMERA_DOCUMENT_FRAME_SIZE FRAMESIZE_SXGA
#define CAMERA_DOCUMENT_JPEG_QUALITY 6
#define CAMERA_DEFAULT_AF_ENABLED true
#define CAMERA_AF_TIMEOUT_MS 1200
#define CAMERA_AF_SETTLE_DELAY_MS 80
#define CAMERA_AF_AUTO_FALLBACK_TIMEOUT_MS 200
#define CAMERA_AF_POST_TRIGGER_DISCARD_FRAMES 1
#define CAMERA_DOCUMENT_BURST_COUNT 3
#define CAMERA_DOCUMENT_BURST_INTERVAL_MS 50
#define CAMERA_DOCUMENT_WARMUP_FRAME_COUNT 1
#define CAMERA_DOCUMENT_OV5640_BRIGHTNESS  2
#define CAMERA_DOCUMENT_OV5640_CONTRAST    1
#define CAMERA_DOCUMENT_OV5640_SHARPNESS   2
#define CAMERA_DOCUMENT_OV5640_AE_LEVEL    2
#define CAMERA_DOCUMENT_OV5640_GAINCEILING GAINCEILING_16X
#define CAMERA_FB_COUNT     1
#define CAMERA_FB_LOCATION  CAMERA_FB_IN_PSRAM
#define CAMERA_GRAB_MODE    CAMERA_GRAB_LATEST
#define CAMERA_HMIRROR      true
#define CAMERA_VFLIP        true
#define CAMERA_OV5640_BRIGHTNESS  2
#define CAMERA_OV5640_CONTRAST    1
#define CAMERA_OV5640_SHARPNESS   2
#define CAMERA_OV5640_AE_LEVEL    2
#define CAMERA_OV5640_GAINCEILING GAINCEILING_16X
#define CAMERA_POWER_LDO_STABILIZE_DELAY_MS 30
#define CAMERA_POWER_EXIT_PWDN_DELAY_MS     30
#define CAMERA_POWER_RESET_PULSE_DELAY_MS   20
#define CAMERA_POWER_RESET_RELEASE_DELAY_MS 100
#define CAMERA_WARMUP_FRAME_COUNT 1
#define CAMERA_DISPLAY_RECOVERY_DELAY_MS 20
#define CAMERA_CAPTURE_MIN_INTERNAL_SRAM_BYTES (32 * 1024)

#define SERVO_OUTPUT_ENABLED 1
#define SERVO_FORCE_CENTER_LOCK 0
#define SERVO_TILT_GPIO      GPIO_NUM_41
#define SERVO_PAN_GPIO       GPIO_NUM_42
#define SERVO_LEDC_TIMER     LEDC_TIMER_0
#define SERVO_PWM_FREQUENCY_HZ 50
#define SERVO_TILT_CHANNEL   LEDC_CHANNEL_4
#define SERVO_PAN_CHANNEL    LEDC_CHANNEL_5
#define SERVO_TILT_MIN_PULSE_US   500
#define SERVO_TILT_CENTER_PULSE_US 1500
#define SERVO_TILT_MAX_PULSE_US   2500
#define SERVO_TILT_MIN_ANGLE      0
#define SERVO_TILT_MAX_ANGLE      180
#define SERVO_TILT_CENTER_ANGLE   90
#define SERVO_TILT_MAX_SPEED_DEG_PER_SEC 180.0f
#define SERVO_PAN_MIN_PULSE_US    500
#define SERVO_PAN_CENTER_PULSE_US 1500
#define SERVO_PAN_MAX_PULSE_US    2500
#define SERVO_PAN_MIN_ANGLE       0
#define SERVO_PAN_MAX_ANGLE       180
#define SERVO_PAN_CENTER_ANGLE    90
#define SERVO_PAN_MAX_SPEED_DEG_PER_SEC 140.0f
#define SERVO_MIN_PULSE_US   SERVO_PAN_MIN_PULSE_US
#define SERVO_CENTER_PULSE_US SERVO_PAN_CENTER_PULSE_US
#define SERVO_MAX_PULSE_US   SERVO_PAN_MAX_PULSE_US
#define SERVO_MIN_ANGLE      0
#define SERVO_MAX_ANGLE      180
#define SERVO_CENTER_ANGLE   SERVO_PAN_CENTER_ANGLE
#define SERVO_MOVE_DURATION_MS 500
#define SERVO_IDLE_TILT_ANGLE  90
#define SERVO_IDLE_PAN_ANGLE   90
#define SERVO_LISTEN_TILT_ANGLE 90

#define CAMERA_DOCUMENT_CAPTURE_TILT_ANGLE 58
#define CAMERA_LOOK_UP_TILT_ANGLE 122
#define CAMERA_LOOK_LEFT_PAN_ANGLE 120
#define CAMERA_LOOK_RIGHT_PAN_ANGLE 60
#define CAMERA_DOCUMENT_CAPTURE_ALIGN_DURATION_MS 160
#define CAMERA_DOCUMENT_CAPTURE_SETTLE_DELAY_MS 60

#endif // _JISHI_S3_BOARD_CONFIG_H_

